// Code generated by goctl. DO NOT EDIT.
// Source: im.proto

package im_client

import (
	"context"

	"easy-chat/apps/im/rpc/im"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = im.Request
	Response = im.Response

	Im interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultIm struct {
		cli zrpc.Client
	}
)

func NewIm(cli zrpc.Client) Im {
	return &defaultIm{
		cli: cli,
	}
}

func (m *defaultIm) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
