// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: apps/im/rpc/im.proto

package im

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Im_Ping_FullMethodName = "/im.Im/Ping"
)

// ImClient is the client API for Im service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type imClient struct {
	cc grpc.ClientConnInterface
}

func NewImClient(cc grpc.ClientConnInterface) ImClient {
	return &imClient{cc}
}

func (c *imClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Im_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImServer is the server API for Im service.
// All implementations must embed UnimplementedImServer
// for forward compatibility
type ImServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedImServer()
}

// UnimplementedImServer must be embedded to have forward compatible implementations.
type UnimplementedImServer struct {
}

func (UnimplementedImServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedImServer) mustEmbedUnimplementedImServer() {}

// UnsafeImServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImServer will
// result in compilation errors.
type UnsafeImServer interface {
	mustEmbedUnimplementedImServer()
}

func RegisterImServer(s grpc.ServiceRegistrar, srv ImServer) {
	s.RegisterService(&Im_ServiceDesc, srv)
}

func _Im_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Im_ServiceDesc is the grpc.ServiceDesc for Im service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Im_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.Im",
	HandlerType: (*ImServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Im_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/im/rpc/im.proto",
}
